"""empty message

Revision ID: cc8c9498b388
Revises: 2b042e543de4
Create Date: 2019-08-23 13:56:34.863945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8c9498b388'
down_revision = '2b042e543de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ft_tag', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ft_tag', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ft_tag', type_='foreignkey')
    op.drop_column('ft_tag', 'owner_id')
    # ### end Alembic commands ###
